### ISSUE TITLE
Request: Mobile phone edition

### ISSUE THREAD

**Issue by Kaminaru** [WinterAlexander/HanziResourcePack#3]
Hello,
Thank you for providing such an amazing opportunity to learn Chinese in a fun and interactive way! I tried setting it up on the mobile version of Minecraft, but it seems it’s not compatible since it uses the Bedrock Edition rather than the Java Edition. Is there a way to make it work on Bedrock?
It would be great to have the option to learn Chinese on the go as well!

**Comment by WinterAlexander** [comment]
Hello there! I was able to generate a pack for bedrock edition using this: https://modifiedcommand.github.io/ConvertJavaTextureToBedrock/

It appears to work pretty well for me (Bedrock, PC):
![image](https://github.com/user-attachments/assets/c8a58a8b-fca9-48b3-a8dc-b6a3953921a0)


I added it to the [downloads ](https://github.com/WinterAlexander/HanziResourcePack/releases/tag/1.0) (Bedrock_Hanzi_Resource_pack_pinyin.zip), let me know if it works for you!

**Comment by Kaminaru** [comment]
**It does work on the ios now. Thank you!**


![minecraft_ios](https://github.com/user-attachments/assets/3d6e42cf-bd36-44ba-bfe3-0d1940181757)

**Comment by WinterAlexander** [comment]
Great thank you for testing!
